# Site settings
title: "Training course for Microsoft AI-050"
description: "Companion Material and Resources for Class Delivery by Ricardo Cabral for Microsoft Official Course AI-050"
url: "https://ai-050.rramoscabral.com/" 
repository: rramoscabral/AI-050---Training---Develop-Generative-AI-Solutions-with-Azure-OpenAI-Service
theme: just-the-docs

# Aux links for the upper right navigation
aux_links:
  "Training for Microsoft Official Course (MOC) AI-050: Develop Generative AI Solutions with Azure OpenAI Service": 
    - "https://ai-050.rramoscabral.com/"

# Color scheme
color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red

# CODE
enable_copy_code_button: true

# Footer content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Companion Material and Resources for Class Delivery by Ricardo Cabral"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html



# Ruby Markdown-superset converter
kramdown:
syntax_highlighter_opts:
  block:
    line_numbers: true
