blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/rramoscabral/AI-050---Training---Develop-Generative-AI-Solutions-with-Azure-OpenAI-Service/discussions
    about: Ask questions and discuss with other community members
